<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<h1><a href="index.phtml"><img src="images/logo.png" alt=""/></a></h1>
		</div>
		<div class="h_left">
			<h2>Bienvenue sur le Gitblog</h2>
			<h3>Un site où lire (et parfois écrire) des articles.</h3>
		</div>
		<div class="h_right">
			<ul class="menu">
				<li><a href="/">home</a></li>
				<li><a href="about.phtml">rédiger un article</a></li>
				<li><a href="/login">connexion</a></li>
				<li><a href="/join">inscription</a></li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>
