
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
<link href="src/public/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!--  jquery plugin -->
<script type="text/javascript" src="src/public/web/js/jquery.min.js"></script>
<!-- start gallery -->
<script type="text/javascript" src="src/public/web/js/jquery.easing.min.js"></script>
<script type="text/javascript" src="src/public/web/js/jquery.mixitup.min.js"></script>
