<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>The Gitblog | Home</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600' rel='stylesheet' type='text/css'>
<link href="src/public/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
<!--  jquery plguin -->
<script type="text/javascript" src="src/public/web/js/jquery.min.js"></script>
<!-- start gallery -->
	<script type="text/javascript" src="src/public/web/js/jquery.easing.min.js"></script>
	<script type="text/javascript" src="src/public/web/js/jquery.mixitup.min.js"></script>
	<script type="text/javascript">
	$(function () {

		var filterList = {

			init: function () {

				// MixItUp plugin
				// http://mixitup.io
				$('#portfoliolist').mixitup({
					targetSelector: '.portfolio',
					filterSelector: '.filter',
					effects: ['fade'],
					easing: 'snap',
					// call the hover effect
					onMixEnd: filterList.hoverEffect()
				});

			},

			hoverEffect: function () {

				// Simple parallax effect
				$('#portfoliolist .portfolio').hover(
					function () {
						$(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
						$(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');
					},
					function () {
						$(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
						$(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');
					}
				);

			}

		};

		// Run the show!
		filterList.init();

	});
	</script>
<!-- Add fancyBox main JS and CSS files -->
<link href="src/public/web/css/magnific-popup.css" rel="stylesheet" type="text/css">
<script src="src/public/web/js/jquery.magnific-popup.js" type="text/javascript"></script>
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>

</head>
<body>
<!-- start header -->
<div class="header_bg">
<div class="wrap">
	<div class="header">
		<div class="logo">
			<h1><a href="index.phtml"><img src="images/logo.png" alt=""/></a></h1>
		</div>
		<div class="h_left">
			<h2>Bienvenue sur le Gitblog</h2>
			<h3>Un site où lire (et parfois écrire) des articles.</h3>
		</div>
		<div class="h_right">
			<ul class="menu">
				<li class="active"><a href="index.phtml">home</a></li>
				<li><a href="">rédiger un article</a></li>
				<li><a href="/login">connexion</a></li>
				<li><a href="/join">inscription</a></li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>
</div>
<!-- start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<!-- start gallery  -->
			<div class="container">
				<!-- no categories for now
					<ul id="filters" class="clearfix">
						<li><span class="filter active" data-filter="app card icon logo web">All</span></li> /
						<li><span class="filter" data-filter="app card logo">design</span></li> /
						<li><span class="filter" data-filter="card app web icon">branding</span></li> /
						<li><span class="filter" data-filter="icon web app">graphic</span></li> /
						<li><span class="filter" data-filter="logo app">animation</span></li> /
						<li><span class="filter" data-filter="web app card logo icon">illustration</span></li> /
						<li><span class="filter" data-filter="web app logo card">photography</span></li>
					</ul>
				-->
		<!-- bientôt remplacé par les données de la bdd -->
		<div id="portfoliolist">
			<?php
				$new1 = array("title" => "l\'assoc MLP ouvre",
											"subtitle" => "les poneys envahissent l'ESGI");
				$new2 = array("title" => "Hervé en cure de désintox",
											"subtitle" => "IL se remet d\'une overdose de cafféine.");
				$new3 = array("title" => "Top 20 des tops les plus putaclic",
											"subtitle" => "La 17e va vous étonner!");
				$new4 = array("title" => "Il jette son bébé par la fenêtre",
											"subtitle" => "Mais quand vous saurez pourquoi ...");
				$new5 = array("title" => "lorem ipsum",
											"subtitle" => "sid amet");
				$news = [$new1, $new2, $new3, $new4, $new5];
				foreach($news as $new) {
			?>
			<a class="popup-with-zoom-anim" href="#small-dialog">
				<div class="portfolio logo1" data-cat="logo">
					<div class="portfolio-wrapper">
						<div class="label">
							<div class="label-text">
								<p class="text-title"><?php echo $new["title"] ?></p>
								<span class="text-category"><?php echo $new["subtitle"] ?></span>
							</div>
							<div class="label-bg"></div>
						</div>
					</div>
				</div>
			</a>
			<?php
				}
			?>
		</div>
	</div><!-- end container -->
	</div>
</div>
</div>
<div class="footer_bg">
<div class="wrap">
	<div class="footer">
		<div>
			<div class="copy">
				<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</div>
</body>
</html>
