<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
	<title>The Gitblog | Home</title>
	<?php include 'includes.phtml' ?>

	<script type="text/javascript">

	$(function () {

		var filterList = {

			init: function () {

				// MixItUp plugin
				// http://mixitup.io
				$('#portfoliolist').mixitup({
					targetSelector: '.portfolio',
					filterSelector: '.filter',
					effects: ['fade'],
					easing: 'snap',
					// call the hover effect
					onMixEnd: filterList.hoverEffect()
				});

			},

			hoverEffect: function () {

				// Simple parallax effect
				$('#portfoliolist .portfolio').hover(
					function () {
						$(this).find('.label').stop().animate({bottom: 0}, 200, 'easeOutQuad');
						$(this).find('img').stop().animate({top: -30}, 500, 'easeOutQuad');
					},
					function () {
						$(this).find('.label').stop().animate({bottom: -40}, 200, 'easeInQuad');
						$(this).find('img').stop().animate({top: 0}, 300, 'easeOutQuad');
					}
				);

			}

		};

		// Run the show!
		filterList.init();

	});
	</script>
<!-- Add fancyBox main JS and CSS files -->
<link href="src/public/web/css/magnific-popup.css" rel="stylesheet" type="text/css">
<script src="src/public/web/js/jquery.magnific-popup.js" type="text/javascript"></script>
		<script>
			$(document).ready(function() {
				$('.popup-with-zoom-anim').magnificPopup({
					type: 'inline',
					fixedContentPos: false,
					fixedBgPos: true,
					overflowY: 'auto',
					closeBtnInside: true,
					preloader: false,
					midClick: true,
					removalDelay: 300,
					mainClass: 'my-mfp-zoom-in'
			});
		});
		</script>

</head>
<body>
 <?php include 'header.phtml' ?>
<!-- start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<!-- start gallery  -->
			<div class="container">
		<!-- bientôt remplacé par les données de la bdd -->
		<div id="portfoliolist">

			<a href="/addnew"><button>ajouter</button></a>
			<?php
				foreach($this->news as $new) :
			?>
			<a href="/new?id=<?php echo $new['id'] ?>">
				<div class="portfolio logo1" data-cat="logo">
					<div class="portfolio-wrapper">
						<div class="label">
							<div class="label-text">
								<p class="text-title"><?php echo $new["title"] ?></p>
								<span class="text-category"><?php echo $new["contenu"] ?></span>
							</div>
							<div class="label-bg"></div>
						</div>
					</div>
				</div>
			</a>
			<?php
				endforeach;
			?>
		</div>
	</div><!-- end container -->
	</div>
</div>
</div>
<div class="footer_bg">
<div class="wrap">
	<div class="footer">
		<div>
			<div class="copy">
				<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</div>
</body>
</html>
