<!DOCTYPE HTML>
<html>
<head>
  <title>The Gitblog | Home</title>
  <?php include 'includes.phtml' ?>
  <link href="src/public/web/css/form.css" rel="stylesheet" type="text/css" media="all" />
</head>

<body>
  <?php include 'header.phtml' ?>
  <!-- start form -->
  <div class="main_bg">
    <div class="wrap">
    	<div class="main">
        <?php $formHandler = "http://" . $_SERVER['SERVER_NAME'] . ":" .  $_SERVER['SERVER_PORT'] . "/join-handle"; ?>
        <form class="form register-form" action="<?php echo $formHandler; ?>" method="post">
          <input type="email" name="email" placeholder="email"/>
          <input type="text" name="login" placeholder="login"/>
          <input type="password" name="pswd" placeholder="password"/>
          <input type="submit" name="inscription"/>
        </form>
      </div>
    </div>
  </div>
</body>
