<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
	<title>The Gitblog | Home</title>
	<?php include 'includes.phtml' ?>
</head>
<body>
 <?php include 'header.phtml' ?>
<!-- start main -->
<div class="main_bg">
<div class="wrap">
	<div class="main">
		<!-- start gallery  -->
		<div class="container">
		
			<p class="text-title"><?php echo $this->new["title"] ?></p>
			<span class="text-category"><?php echo $this->new["contenu"] ?></span><br>
		</div>
		<a href="/modify?id=<?php echo $this->new["id"]?>"><button>modifier</button></a>
	</div>
</div>
</div>
<div class="footer_bg">
<div class="wrap">
	<div class="footer">
		<div>
			<div class="copy">
				<p class="link"><span>© All rights reserved | Template by&nbsp;<a href="http://w3layouts.com/"> W3Layouts</a></span></p>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</div>
</div>
</body>
</html>
